"""add like column to pokemon table

Revision ID: 0366d0f1c6c8
Revises: 44cf9d4118a8
Create Date: 2024-02-28 12:07:33.939613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0366d0f1c6c8'
down_revision = '44cf9d4118a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('like')

    # ### end Alembic commands ###
