"""add likes coulumn in poke

Revision ID: 654dfeda7d97
Revises: 
Create Date: 2024-02-28 23:21:49.381071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654dfeda7d97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
